name: Auto Rebase and Merge

on:
  pull_request:
    types: [labeled]

permissions:
  pull-requests: write
  contents: write

jobs:
  rebase-and-merge:
    name: Rebase and Merge PR
    if: github.event.label.name == 'rebase-and-merge'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.8
        with:
          autosquash: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create merge commit
        uses: actions/github-script@v6
        with:
          script: |
            const pullNumber = context.payload.pull_request.number;

            console.log(`Merging PR #${pullNumber} into main via merge commit...`);

            const response = await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pullNumber,
              merge_method: 'merge', 
            });

            if (response.status !== 200) {
              core.setFailed(`Merge failed: ${response.status} - ${response.data.message}`);
            } else {
              console.log(`PR #${pullNumber} merged successfully!`);
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
