name: Secure Auto Rebase and Merge

on:
  pull_request:
    types: [labeled]

permissions:
  pull-requests: write
  contents: write
  checks: read  # Чтобы проверять CI/CD статусы
  repository-projects: read  # Чтобы получать список Collaborators

jobs:
  rebase-and-merge:
    name: Secure Rebase and Merge PR
    if: github.event.label.name == 'rebase-and-merge'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.8
        with:
          autosquash: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create merge commit with security checks
        uses: actions/github-script@v6
        with:
          script: |
            const pullNumber = context.payload.pull_request.number;
            const prUser = context.payload.pull_request.user.login;
            const labelName = 'rebase-and-merge';

            async function removeLabel() {
              try {
                await github.rest.issues.removeLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: pullNumber,
                  name: labelName,
                });
                console.log(`Label '${labelName}' removed from PR #${pullNumber}.`);
              } catch (error) {
                console.error(`Failed to remove label: ${error.message}`);
              }
            }

            console.log(`Fetching collaborators for repo...`);
            const { data: collaborators } = await github.rest.repos.listCollaborators({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const allowedUsers = collaborators
              .filter(user => user.permissions.push || user.permissions.admin)
              .map(user => user.login);

            if (!allowedUsers.includes(prUser)) {
              core.setFailed(`User ${prUser} is not authorized to auto-merge.`);
              await removeLabel();
              return;
            }

            console.log(`Checking CI/CD status for PR #${pullNumber}...`);

            // 1. Получаем все check_runs
            const { data: checks } = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.sha,
            });

            // 2. Указываем список "обязательных" проверок
            const requiredChecks = ['build', 'test']; // Пример! Подставьте свои

            // 3. Фильтруем из всех только нужные
            const relevantCheckRuns = checks.check_runs.filter(check => 
              requiredChecks.includes(check.name)
            );

            // 4. Проверяем, не упали ли наши обязательные проверки
            const failedRequiredCheck = relevantCheckRuns.some(check => 
              check.conclusion === 'failure'
            );

            if (failedRequiredCheck) {
              core.setFailed("Some required checks have failed. Merge is blocked.");
              await removeLabel();
              return;
            }

            // (Опционально) Проверяем, что все обязательные проверки завершились (нет in_progress)
            const notCompleted = relevantCheckRuns.some(check =>
              check.status !== 'completed'
            );
            
            if (notCompleted) {
              core.setFailed("Some required checks are still running. Please wait.");
              await removeLabel();
              return;
            }

            console.log(`Checking merge conflicts for PR #${pullNumber}...`);

            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pullNumber
            });

            if (pr.mergeable_state !== "clean") {
              console.log(`mergeable: ${pr.mergeable}`);
              console.log(`mergeable_state: ${pr.mergeable_state}`);
              console.log(`mergeable_reason: ${pr.mergeable_reason}`);
              core.setFailed(`Merge conflict detected! PR #${pullNumber} requires manual resolution.`);
              await removeLabel();
              return;
            }

            console.log(`Merging PR #${pullNumber} into main via merge commit...`);

            const response = await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pullNumber,
              merge_method: 'merge', 
            });

            if (response.status !== 200) {
              core.setFailed(`Merge failed: ${response.status} - ${response.data.message}`);
              await removeLabel();
            } else {
              console.log(`PR #${pullNumber} merged successfully!`);
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
